[build]
  publish = "dist/spa"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/packages/active"
  to = "/.netlify/functions/packages"
  status = 200

[[redirects]]
  from = "/api/packages*"
  to = "/.netlify/functions/packages-admin"
  status = 200

[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  targetPort = 8080
  port = 3000
