[build]
  publish = "dist/spa"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/.netlify/functions/packages-admin/*"
  to = "/.netlify/functions/packages-admin"
  status = 200

[[redirects]]
  from = "/.netlify/functions/packages-admin"
  to = "/.netlify/functions/packages-admin"
  status = 200

[[redirects]]
  from = "/.netlify/functions/packages"
  to = "/.netlify/functions/packages"
  status = 200

[[redirects]]
  from = "/api/packages"
  to = "/.netlify/functions/packages"
  status = 200

[[redirects]]
  from = "/api/packages/*"
  to = "/.netlify/functions/packages-admin"
  status = 200

[[redirects]]
  from = "/api/auth/login"
  to = "/.netlify/functions/login"
  status = 200

[[redirects]]
  from = "/api/auth/verify"
  to = "/.netlify/functions/verify"
  status = 200

[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/api/stats"
  to = "/.netlify/functions/stats"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  targetPort = 8080
  port = 3000
