[build]
  command = "npm run build:client"
  functions = "netlify/functions"
  publish = "dist/spa"

[functions]
  external_node_modules = ["express", "@neondatabase/serverless", "pg"]
  node_bundler = "esbuild"
  
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/neon-api/:splat"

# Environment variables (set these in Netlify dashboard)
# DATABASE_URL = "your_neon_connection_string_here"
# JWT_SECRET = "your_jwt_secret_here"
# NODE_ENV = "production"
